import type { Language } from './copy';

/* The geometry, import and export code throws plain English messages, since
   it runs in workers and tests without a language. The Arabic site shows them
   through localizeError: exact messages first, then the patterns that carry
   a value (a field name, a range, an entity type). Anything not listed is
   shown as it is. */

/** Field names used in range messages, as the forms label them. */
const FIELDS: Record<string, string> = {
  Border: 'الحافة', Bore: 'ثقب المحور', Bridge: 'الجسر', Clearance: 'الخلوص', Colours: 'الألوان', Columns: 'الأعمدة', Copies: 'النسخ',
  'Corner radius': 'نصف قطر الزاوية', Corners: 'الزوايا', 'Cut speed': 'سرعة القص', DPI: 'الدقة DPI', Depth: 'العمق', Detail: 'التفاصيل',
  'Dogbone radius': 'نصف قطر التفريغ', 'Edge margin': 'هامش الحافة', 'End margin': 'هامش الطرف', 'Engrave speed': 'سرعة الحفر',
  'Finger width': 'عرض الأصبع', Gap: 'الفراغ', 'Hand hole distance from top': 'بعد فتحة اليد عن الأعلى', 'Hand hole height': 'ارتفاع فتحة اليد',
  'Hand hole width': 'عرض فتحة اليد', Height: 'الارتفاع', 'Hinge zone': 'منطقة المفصل', 'Hole size': 'مقاس الثقب', Hole: 'الثقب',
  'Join distance': 'مسافة ربط الفجوات', 'Kerf compensation': 'تعويض عرض القص', Labour: 'العمالة', Length: 'الطول', 'Line spacing': 'تباعد الأسطر',
  'Machine minutes': 'دقائق الماكينة', 'Machine rate': 'أجرة ساعة الماكينة', Margin: 'الهامش', 'Material thickness': 'سماكة الخامة',
  'Maximum power': 'أقصى قدرة', 'Maximum speed': 'أقصى سرعة', 'Minimum area': 'أصغر مساحة', 'Minimum power': 'أدنى قدرة', 'Minimum speed': 'أدنى سرعة',
  Module: 'الموديول', Overhead: 'المصاريف العامة', Overlap: 'التداخل', 'Panel spacing': 'تباعد الألواح', 'Piece size': 'مقاس القطعة',
  'Pierce time': 'زمن الثقب', 'Pixel height': 'الارتفاع بالبكسل', 'Pixel width': 'العرض بالبكسل', 'Pressure angle': 'زاوية الضغط',
  'Print height': 'ارتفاع الطباعة', 'Print width': 'عرض الطباعة', Profit: 'الربح', 'Pull size': 'مقاس المقبض', Quantity: 'الكمية', Rows: 'الصفوف',
  'Second gear teeth': 'أسنان الترس الثاني', 'Sheet height': 'ارتفاع اللوح', 'Sheet price': 'سعر اللوح', 'Sheet width': 'عرض اللوح', Sheets: 'الألواح',
  'Simplify tolerance': 'انحراف التبسيط', 'Slit length': 'طول الشق', Slots: 'الفتحات', Smoothing: 'التنعيم', Spacing: 'التباعد',
  'Square size': 'مقاس المربع', Step: 'الخطوة', 'Tab size': 'مقاس اللسان', 'Text height': 'ارتفاع النص', Threshold: 'العتبة',
  'Travel allowance': 'زمن التنقل', Finishing: 'التشطيب', 'Minimum price': 'الحد الأدنى للسعر', Wall: 'الجدار', Width: 'العرض', 'Image width': 'عرض الصورة', 'Image height': 'ارتفاع الصورة',
};
const field = (name: string) => FIELDS[name] ?? name;

const EXACT: Record<string, string> = {
  '3D, mesh or fitted POLYLINE is unsupported. Export ordinary 2D polylines.': 'خطوط POLYLINE الثلاثية الأبعاد أو الشبكية أو الملائَمة غير مدعومة. صدّر خطوطاً ثنائية الأبعاد عادية.',
  'A panel is too large for the browser to draw. Lower the print resolution or split into more panels.': 'إحدى اللوحات أكبر من أن يرسمها المتصفح. اخفض دقة الطباعة أو قسّم إلى لوحات أكثر.',
  'A plate with rounded ends takes two holes, at the sides.': 'اللوحة ذات الطرفين المستديرين تأخذ ثقبين على الجانبين.',
  'ARC has a zero sweep.': 'القوس ARC بلا امتداد.',
  'Binary DXF is unsupported; export ASCII DXF.': 'ملفات DXF الثنائية غير مدعومة. صدّر الملف بصيغة ASCII DXF.',
  'Box outline tracing failed.': 'تعذّر تتبّع حدود الصندوق.',
  'Bulged segment has coincident endpoints.': 'مقطع منحنٍ طرفاه في النقطة نفسها.',
  'Canvas is unavailable in this browser.': 'الرسم غير متاح في هذا المتصفح.',
  'Canvas is unavailable.': 'الرسم غير متاح في هذا المتصفح.',
  'Circle and ellipse radii must be positive.': 'نصف قطر الدائرة والشكل البيضاوي يجب أن يكون أكبر من صفر.',
  'Circle or arc radius must be positive.': 'نصف قطر الدائرة أو القوس يجب أن يكون أكبر من صفر.',
  'Closed SPLINE endpoints do not meet. Export a closed polyline.': 'طرفا منحنى SPLINE المغلق لا يلتقيان. صدّره كخط مغلق.',
  'Converted CDR exceeds the output size limit.': 'ملف CDR بعد التحويل أكبر من الحد المسموح.',
  'Could not weld these outlines.': 'تعذّر دمج هذه الحدود.',
  'Curve exceeds the 20,000 node limit.': 'المنحنى يتجاوز حد ٢٠٬٠٠٠ نقطة.',
  'Curve has zero radius.': 'المنحنى نصف قطره صفر.',
  'Discontinuous SPLINE is unsupported. Split it into separate paths.': 'منحنى SPLINE المتقطع غير مدعوم. قسّمه إلى مسارات منفصلة.',
  'Dividers need more inside height. Increase the box height.': 'الفواصل تحتاج ارتفاعاً داخلياً أكبر. زد ارتفاع الصندوق.',
  'Drawing exceeds the 1,000,000 node limit. Simplify curves before importing.': 'التصميم يتجاوز حد مليون نقطة. بسّط المنحنيات قبل الاستيراد.',
  'Drawing exceeds the 20,000 shape limit.': 'التصميم يتجاوز حد ٢٠٬٠٠٠ شكل.',
  'Duplicate ENTITIES section.': 'قسم ENTITIES مكرر في الملف.',
  'ELLIPSE has an invalid axis ratio.': 'نسبة محاور الشكل البيضاوي ELLIPSE غير صالحة.',
  'Empty geometry.': 'لا توجد أشكال.',
  'Enter a physical width in mm: SVG dimensions are missing or percentage based.': 'أدخل العرض الفعلي بالملليمتر: أبعاد ملف SVG مفقودة أو بالنسبة المئوية.',
  'Entity is missing its type.': 'عنصر في الملف بلا نوع.',
  'Export contains an invalid dimension.': 'الملف المصدّر فيه مقاس غير صالح.',
  'File exceeds the 32 MB limit.': 'الملف أكبر من حد ٣٢ ميغابايت.',
  'Fit-point-only SPLINE is unsupported; export control points or flatten it to a polyline.': 'منحنى SPLINE بنقاط ملاءمة فقط غير مدعوم. صدّره بنقاط التحكم أو حوّله إلى خط متعدد.',
  'Fitted or 3D VERTEX is unsupported.': 'نقاط VERTEX الملائَمة أو الثلاثية الأبعاد غير مدعومة.',
  'Geometry contains non-finite coordinates.': 'الأشكال فيها إحداثيات غير صالحة.',
  'Give one quantity for every part.': 'أدخل كمية لكل قطعة.',
  'Gradient definitions must be inside defs.': 'تعريفات التدرج يجب أن تكون داخل defs.',
  'Image data must be RGBA.': 'بيانات الصورة يجب أن تكون RGBA.',
  'Image dimensions must be positive whole numbers.': 'أبعاد الصورة يجب أن تكون أعداداً صحيحة موجبة.',
  'Invalid DXF group code.': 'رمز مجموعة غير صالح في ملف DXF.',
  'Invalid INSUNITS header.': 'ترويسة الوحدات INSUNITS غير صالحة.',
  'Invalid POLYLINE vertex.': 'نقطة غير صالحة في POLYLINE.',
  'Invalid SVG document.': 'ملف SVG غير صالح.',
  'Invalid SVG path arc.': 'قوس غير صالح في مسار SVG.',
  'Invalid SVG path close command.': 'أمر إغلاق غير صالح في مسار SVG.',
  'Invalid SVG path coordinates.': 'إحداثيات غير صالحة في مسار SVG.',
  'Invalid SVG path data.': 'بيانات مسار SVG غير صالحة.',
  'Invalid SVG path: command expected.': 'مسار SVG غير صالح: يُنتظر أمر رسم.',
  'Invalid SVG transform.': 'تحويل SVG غير صالح.',
  'Invalid SVG viewBox.': 'قيمة viewBox غير صالحة في ملف SVG.',
  'Invalid coordinate or number.': 'إحداثي أو رقم غير صالح.',
  'Invalid matrix transform.': 'تحويل matrix غير صالح.',
  'Invalid or incomplete SVG path command.': 'أمر مسار SVG غير صالح أو ناقص.',
  'Invalid polygon/polyline points.': 'نقاط المضلع أو الخط المتعدد غير صالحة.',
  'Invalid rotate transform.': 'تحويل الدوران rotate غير صالح.',
  'Invalid scale transform.': 'تحويل التحجيم scale غير صالح.',
  'Invalid shape coordinates.': 'إحداثيات الشكل غير صالحة.',
  'Invalid skew transform.': 'تحويل الإمالة skew غير صالح.',
  'Invalid translate transform.': 'تحويل الإزاحة translate غير صالح.',
  'JPEG sides must be between 1 and 65,535 pixels.': 'أضلاع صورة JPEG يجب أن تكون بين ١ و٦٥٬٥٣٥ بكسل.',
  'Kerf compensation must be smaller than half a finger. Reduce kerf or use wider fingers.': 'تعويض عرض القص يجب أن يكون أصغر من نصف الأصبع. قلّل التعويض أو استخدم أصابع أعرض.',
  'LWPOLYLINE vertex count does not match.': 'عدد نقاط LWPOLYLINE لا يطابق المذكور.',
  'Malformed ASCII DXF group pairs.': 'أزواج المجموعات في ملف DXF تالفة.',
  'Malformed DXF end of file.': 'نهاية ملف DXF تالفة.',
  'Malformed DXF section.': 'قسم تالف في ملف DXF.',
  'Malformed SPLINE control points or knot count.': 'نقاط التحكم أو العقد في منحنى SPLINE تالفة.',
  'Margins, gaps and bleed cannot be negative.': 'الهوامش والفراغات والزيادة لا يمكن أن تكون سالبة.',
  'Missing ENTITIES section or EOF; expected a complete ASCII DXF file.': 'قسم ENTITIES أو نهاية الملف مفقودة. الملف المتوقع DXF كامل بصيغة ASCII.',
  'Missing required coordinate or number.': 'إحداثي أو رقم مطلوب مفقود.',
  'More rows than the image height.': 'عدد الصفوف أكبر من ارتفاع الصورة.',
  'Move the hole further from the edge.': 'أبعد الثقب عن الحافة.',
  'Nested SVG viewports are unsupported. Flatten the export first.': 'عناصر svg المتداخلة غير مدعومة. سطّح الملف قبل التصدير.',
  'Nesting needs closed, non-empty outlines. Use Vector cleanup to inspect open paths.': 'الترتيب يحتاج حدوداً مغلقة. استخدم تنظيف الفيكتور لفحص المسارات المفتوحة.',
  'No cut geometry found in ENTITIES.': 'لا توجد أشكال للقص في الملف.',
  'No hole fits. Reduce the margin or the hole size.': 'لا يتسع أي ثقب. قلّل الهامش أو مقاس الثقب.',
  'No image loaded.': 'لم تُحمَّل صورة.',
  'No vector pages were found in this CDR file.': 'لا توجد صفحات فيكتور في ملف CDR هذا.',
  'Not a JPEG file.': 'الملف ليس صورة JPEG.',
  'Nothing is left at that offset. An inward offset may be larger than the shape.': 'لم يبقَ شيء بهذه الإزاحة. قد تكون الإزاحة الداخلية أكبر من الشكل.',
  'Offset must be between -500 and 500 mm.': 'الإزاحة يجب أن تكون بين ‎-500 و500 مم.',
  'Only default xMidYMid meet preserveAspectRatio is supported.': 'قيمة preserveAspectRatio المدعومة هي الافتراضية xMidYMid meet فقط.',
  'Outlines must be between 1 and 6.': 'عدد الحدود يجب أن يكون بين ١ و٦.',
  'POLYLINE is missing SEQEND.': 'خط POLYLINE بلا نهاية SEQEND.',
  'Physical width must be a positive number in mm.': 'العرض الفعلي يجب أن يكون رقماً موجباً بالملليمتر.',
  'Physical width must be positive and the drawing must have nonzero width.': 'العرض الفعلي يجب أن يكون موجباً، والتصميم يجب أن يكون له عرض.',
  'Polyline needs at least two vertices.': 'الخط المتعدد يحتاج نقطتين على الأقل.',
  'Polyline vertex data is out of order.': 'بيانات نقاط الخط المتعدد بترتيب خاطئ.',
  'Polyline vertex is missing a coordinate.': 'نقطة في الخط المتعدد بلا إحداثي.',
  'Print width must be above zero.': 'عرض الطباعة يجب أن يكون أكبر من صفر.',
  'Quantities must be whole numbers.': 'الكميات يجب أن تكون أعداداً صحيحة.',
  'Rectangle corner radii must be nonnegative.': 'نصف قطر زوايا المستطيل لا يمكن أن يكون سالباً.',
  'Rectangle dimensions must be positive.': 'أبعاد المستطيل يجب أن تكون أكبر من صفر.',
  'SPLINE cannot be flattened accurately within the complexity limit.': 'لا يمكن تحويل منحنى SPLINE بدقة ضمن حد التعقيد.',
  'SPLINE exceeds the 20,000 node limit.': 'منحنى SPLINE يتجاوز حد ٢٠٬٠٠٠ نقطة.',
  'SPLINE knots must be ordered with a nonzero domain.': 'عقد منحنى SPLINE يجب أن تكون مرتبة وبمجال غير صفري.',
  'SPLINE requires one positive weight per control point.': 'منحنى SPLINE يحتاج وزناً موجباً لكل نقطة تحكم.',
  'SVG curve exceeds subdivision limit. Simplify the export.': 'منحنى في ملف SVG يتجاوز حد التقسيم. بسّط الملف.',
  'SVG dimensions must be positive.': 'أبعاد ملف SVG يجب أن تكون أكبر من صفر.',
  'SVG document types, entities and external stylesheets are unsupported.': 'تعريفات DOCTYPE والكيانات وأنماط CSS الخارجية غير مدعومة في SVG.',
  'SVG exceeds 1,000,000 vertices. Simplify curves or reduce physical size.': 'ملف SVG يتجاوز مليون نقطة. بسّط المنحنيات أو صغّر المقاس.',
  'SVG exceeds 20,000 shapes.': 'ملف SVG يتجاوز ٢٠٬٠٠٠ شكل.',
  'SVG exceeds the 32 MB limit.': 'ملف SVG أكبر من حد ٣٢ ميغابايت.',
  'SVG exceeds the geometry processing limit. Simplify the export.': 'ملف SVG يتجاوز حد المعالجة. بسّط الملف.',
  'SVG groups exceed 32 nesting levels.': 'المجموعات في ملف SVG متداخلة لأكثر من ٣٢ مستوى.',
  'SVG is too complex: at most 50,000 elements.': 'ملف SVG معقد جداً: الحد ٥٠٬٠٠٠ عنصر.',
  'SVG needs a viewBox or both dimensions to determine its aspect ratio.': 'ملف SVG يحتاج viewBox أو العرض والارتفاع معاً لمعرفة نسبته.',
  'SVG path is too complex.': 'مسار SVG معقد جداً.',
  'SVG paths must begin with a move command.': 'مسارات SVG يجب أن تبدأ بأمر انتقال M.',
  'SVG physical dimensions exceed 100,000 mm.': 'أبعاد ملف SVG تتجاوز ١٠٠٬٠٠٠ مم.',
  'Scaled geometry exceeds numeric limits.': 'الأشكال بعد التحجيم تتجاوز الحدود الرقمية.',
  'Size must be above zero.': 'المقاس يجب أن يكون أكبر من صفر.',
  'Sticker width must be above zero.': 'عرض الملصق يجب أن يكون أكبر من صفر.',
  'That is more than 6,000 holes. Make the holes larger.': 'هذا أكثر من ٦٬٠٠٠ ثقب. كبّر الثقوب.',
  'That makes more than 200 panels. Check the sizes.': 'هذا ينتج أكثر من ٢٠٠ لوحة. راجع المقاسات.',
  'The AI model could not be downloaded. Check the connection and try again.': 'تعذّر تنزيل نموذج الذكاء الاصطناعي. تحقق من الاتصال وحاول مجدداً.',
  'The CDR converter returned an unreadable document.': 'محوّل CDR أعاد ملفاً لا يمكن قراءته.',
  'The design could not be encoded.': 'تعذّر حفظ التصميم.',
  'The drawing has no closed outlines to offset.': 'لا توجد في التصميم حدود مغلقة للإزاحة.',
  'The holes do not fit in the margin. Widen the margin or use smaller holes.': 'الثقوب لا تتسع في الهامش. وسّع الهامش أو استخدم ثقوباً أصغر.',
  'The margin must be above zero.': 'الهامش يجب أن يكون أكبر من صفر.',
  'The model is not loaded.': 'النموذج غير محمّل.',
  'The offset is too large for this picture size. Lower the offset or use a smaller picture.': 'الإزاحة كبيرة على مقاس هذه الصورة. قلّل الإزاحة أو استخدم صورة أصغر.',
  'The panel could not be encoded. Try a lower resolution.': 'تعذّر حفظ اللوحة. جرّب دقة أقل.',
  'The roll must be wider than the overlap plus both borders.': 'عرض الرول يجب أن يكون أكبر من التداخل والحافتين معاً.',
  'The text is too long for this tag. Shorten it or make the tag wider.': 'النص أطول من البطاقة. قصّره أو وسّع البطاقة.',
  'There is no room for text below the hole. Make the tag larger or the hole smaller.': 'لا مكان للنص تحت الثقب. كبّر البطاقة أو صغّر الثقب.',
  'This DXF contains only text. Convert text to curves before importing.': 'ملف DXF هذا فيه نصوص فقط. حوّل النصوص إلى منحنيات قبل الاستيراد.',
  'This SVG contains only text. Convert text to curves in CorelDRAW or Illustrator before importing.': 'ملف SVG هذا فيه نصوص فقط. حوّل النصوص إلى منحنيات في CorelDRAW أو Illustrator قبل الاستيراد.',
  'SVG contains no usable paths. Convert artwork to curves before exporting.': 'لا توجد مسارات صالحة في ملف SVG. حوّل التصميم إلى منحنيات قبل التصدير.',
  'This file is not a font HarfBuzz can read.': 'هذا الملف ليس خطاً يمكن قراءته.',
  'This font file is damaged.': 'ملف الخط تالف.',
  'This image could not be opened. Try saving it again as PNG or JPEG.': 'تعذّر فتح الصورة. جرّب حفظها مجدداً بصيغة PNG أو JPEG.',
  'This nesting job is too detailed even with 2 mm outline simplification. Nest fewer parts at once.': 'عمل الترتيب مفصّل جداً حتى بعد تبسيط الحدود ٢ مم. رتّب قطعاً أقل في المرة الواحدة.',
  'Too many hinge lines. Widen the spacing or narrow the zone.': 'خطوط المفصل كثيرة جداً. وسّع التباعد أو ضيّق المنطقة.',
  'Transformed SVG coordinates exceed supported limits.': 'إحداثيات SVG بعد التحويل تتجاوز الحدود المدعومة.',
  'Unexpected ENDSEC.': 'نهاية قسم ENDSEC في غير مكانها.',
  'Unsupported LWPOLYLINE flags.': 'خصائص LWPOLYLINE غير مدعومة.',
  'Unsupported SPLINE degree or flags; supported degrees are 1–5.': 'درجة منحنى SPLINE أو خصائصه غير مدعومة. الدرجات المدعومة من ١ إلى ٥.',
  'Unsupported SVG CSS: stylesheet. Export plain paths.': 'أنماط CSS في ملف SVG غير مدعومة. صدّر مسارات بسيطة.',
  'Unsupported SVG dimension unit. Use mm, cm, in, pt, pc or px.': 'وحدة أبعاد SVG غير مدعومة. استخدم mm أو cm أو in أو pt أو pc أو px.',
  'Unsupported SVG path command.': 'أمر مسار SVG غير مدعوم.',
  'Use a CDR file with at most 100 pages.': 'استخدم ملف CDR فيه ١٠٠ صفحة على الأكثر.',
  'Use whole-number rows and columns, up to 500 repeated shapes.': 'استخدم أعداداً صحيحة للصفوف والأعمدة، حتى ٥٠٠ شكل مكرر.',
  'Use whole-number slots and keep every slot width above zero.': 'استخدم عدداً صحيحاً للفتحات، واجعل عرض كل فتحة أكبر من صفر.',
  'Viewing distance must be above zero.': 'مسافة المشاهدة يجب أن تكون أكبر من صفر.',
  'Wide polylines are unsupported; convert their outline to closed paths.': 'الخطوط المتعددة العريضة غير مدعومة. حوّل حدودها إلى مسارات مغلقة.',
  'This file is unitless. Choose mm, cm or inches explicitly.': 'هذا الملف بلا وحدة قياس. اختر mm أو cm أو inches.',
  'Invalid settings.': 'إعدادات غير صالحة.',
  'Repair failed.': 'تعذّر إصلاح الملف.',
  'Import failed.': 'تعذّر الاستيراد.',
  'Page import failed.': 'تعذّر استيراد الصفحة.',
  'Worker failed.': 'تعذّر تشغيل المعالجة في المتصفح.',
  'Nesting failed.': 'تعذّر الترتيب.',
  'Engraving preparation failed.': 'تعذّر تجهيز صورة الحفر.',
  'Image import failed.': 'تعذّر استيراد الصورة.',
  'Lettering failed.': 'تعذّر إنشاء الكتابة.',
  'Nesting could not finish. Reduce the job size and try again.': 'تعذّر إكمال الترتيب. قلّل عدد القطع وحاول مجدداً.',
  'Offset failed.': 'تعذّرت الإزاحة.',
  'Saving failed.': 'تعذّر الحفظ.',
  'The sheet could not be saved.': 'تعذّر حفظ الورقة.',
  'The font could not be loaded.': 'تعذّر تحميل الخط.',
  'This image could not be opened. Very large files may need to be saved as JPEG first.': 'تعذّر فتح الصورة. الملفات الكبيرة جداً قد تحتاج حفظها بصيغة JPEG أولاً.',
  'This image could not be opened.': 'تعذّر فتح الصورة.',
  'Upscaling failed.': 'تعذّر تكبير الصورة.',
  'Bit diameter must be between 0 and 50 mm.': 'قطر الريشة يجب أن يكون بين 0 و50 مم.',
  'Corner angle must be between 60 and 179 degrees.': 'زاوية الركن يجب أن تكون بين 60 و179 درجة.',
  'Use 0 to 12 tabs per part.': 'استخدم من 0 إلى 12 جسراً لكل قطعة.',
  'Tab width must be between 0 and 50 mm.': 'عرض الجسر يجب أن يكون بين 0 و50 مم.',
  'Write at least one name, one per line.': 'اكتب اسماً واحداً على الأقل، اسماً في كل سطر.',
  'No outlines for this name.': 'لا توجد حدود لهذا الاسم.',
  'Bridge width must be above zero.': 'عرض الجسر يجب أن يكون أكبر من صفر.',
  'The artwork has no width or height to resize.': 'التصميم بلا عرض أو ارتفاع لتغيير مقاسه.',
  'Vectorizing failed.': 'تعذّر التحويل إلى فيكتور.',
};

const PATTERNS: [RegExp, (...m: string[]) => string][] = [
  [/^(.+) must be between (-?[\d.,]+) and (-?[\d.,]+)\.$/, (name, min, max) => `${field(name)} يجب أن يكون بين ${min} و${max}.`],
  [/^(.+) must be above zero\.$/, name => `${field(name)} يجب أن يكون أكبر من صفر.`],
  [/^(.+): enter a value from (-?[\d.,]+) to (-?[\d.,]+)\.$/, (name, min, max) => `${field(name)}: أدخل قيمة من ${min} إلى ${max}.`],
  [/^(.+): use a whole number\.$/, name => `${field(name)}: استخدم عدداً صحيحاً.`],
  [/^Invalid (.+) value\. Use unitless geometry coordinates\.$/, name => `قيمة ${name} غير صالحة. استخدم إحداثيات بلا وحدات.`],
  [/^Invalid (.+) numbers\.$/, name => `أرقام ${name} غير صالحة.`],
  [/^(.+) exceeds supported coordinates\.$/, name => `${name} يتجاوز الإحداثيات المدعومة.`],
  [/^(\w+) has an unsupported extrusion plane\. Flatten it before export\.$/, type => `العنصر ${type} على مستوى غير مدعوم. سطّحه قبل التصدير.`],
  [/^(\w+) has no usable length\.$/, type => `العنصر ${type} بلا طول صالح.`],
  [/^(\w+) is in paper space; export model-space geometry only\.$/, type => `العنصر ${type} في مساحة الورق. صدّر أشكال مساحة النموذج فقط.`],
  [/^(\w+) uses a 3D plane, elevation or thickness\. Export flat 2D geometry\.$/, type => `العنصر ${type} ثلاثي الأبعاد أو له ارتفاع أو سماكة. صدّر أشكالاً ثنائية الأبعاد.`],
  [/^Unsupported entity (\w+)\. Convert it to flat LINE, POLYLINE, LWPOLYLINE, CIRCLE, ARC, ELLIPSE or SPLINE geometry before import\.$/, type => `العنصر ${type} غير مدعوم. حوّله إلى LINE أو POLYLINE أو LWPOLYLINE أو CIRCLE أو ARC أو ELLIPSE أو SPLINE قبل الاستيراد.`],
  [/^Unsupported INSUNITS (.+); choose the source unit explicitly\.$/, units => `وحدة الملف INSUNITS ${units} غير مدعومة. اختر وحدة المصدر يدوياً.`],
  [/^Unsafe or referenced SVG content: (.+)\. Expand references to paths first\.$/, name => `محتوى غير آمن أو مرتبط في ملف SVG: ${name}. حوّل الروابط إلى مسارات أولاً.`],
  [/^Unsupported SVG CSS selector: (.+)\. Export plain paths\.$/, name => `محدد CSS غير مدعوم في ملف SVG: ${name}. صدّر مسارات بسيطة.`],
  [/^Unsupported SVG CSS: (.+)\. Export plain paths\.$/, name => `خاصية CSS غير مدعومة في ملف SVG: ${name}. صدّر مسارات بسيطة.`],
  [/^Unsupported SVG effect: (.+)\. Flatten effects before importing\.$/, name => `تأثير غير مدعوم في ملف SVG: ${name}. سطّح التأثيرات قبل الاستيراد.`],
  [/^Unsupported SVG element: (.+)\. Export plain paths without effects or embedded content\.$/, name => `عنصر غير مدعوم في ملف SVG: ${name}. صدّر مسارات بسيطة بلا تأثيرات أو محتوى مضمّن.`],
  [/^Unsupported SVG transform: (.+)\.$/, name => `تحويل SVG غير مدعوم: ${name}.`],
  [/^Use 1–(\d+) total parts\.$/, max => `استخدم من ١ إلى ${max} قطعة.`],
  [/^A batch makes up to (\d+) tags\.$/, max => `الدفعة الواحدة حتى ${max} بطاقة.`],
  [/^These names do not fit the tag: (.+)\. Make the tag wider or the letters smaller\.$/, names => `هذه الأسماء لا تتسع في البطاقة: ${names}. وسّع البطاقة أو صغّر الحروف.`],
  [/^Images are limited to (.+) pixels\.$/, max => `الحد الأقصى للصورة ${max} بكسل.`],
  [/^Engraving font has no glyph for "(.+)"\.$/, char => `خط الحفر لا يحتوي الحرف «${char}».`],
  [/^Box (\w+) is too small for ([\d.]+) mm material\. Use at least ([\d.]+) mm outside\.$/, (key, t, min) => `${field(key[0].toUpperCase() + key.slice(1))} للصندوق صغير على خامة ${t} مم. استخدم ${min} مم على الأقل من الخارج.`],
  [/^Too many (.+) for this box\. Each compartment needs at least ([\d.]+) mm\.$/, (name, min) => `عدد ${name} كبير على هذا الصندوق. كل قسم يحتاج ${min} مم على الأقل.`],
  [/^(.+) does not fit on (.+)\. Make it smaller or move it away from edges and joints\.$/, (cut, part) => `${cut} لا يتسع على ${part}. صغّره أو أبعده عن الحواف والوصلات.`],
  [/^Use at most (\d+) squares: cutting software gives each colour its own layer, and LightBurn has 30\.$/, max => `استخدم ${max} مربعاً على الأكثر: برامج القص تعطي كل لون طبقة، وفي LightBurn ثلاثون طبقة.`],
];

/** The message in the page's language. */
export function localizeError(message: string, lang: Language): string {
  if (lang !== 'ar' || !message) return message;
  const dxf = message.startsWith('DXF: ');
  const text = dxf ? message.slice(5) : message;
  let out = EXACT[text];
  if (!out) for (const [pattern, write] of PATTERNS) { const m = pattern.exec(text); if (m) { out = write(...m.slice(1)); break; } }
  return out ? (dxf ? `DXF: ${out}` : out) : message;
}
